SELECT TABLE_NAME from INFORMATION_SCHEMA.TABLES ;
Exec sp_columns Diagnosis

/*1*/
ALTER TABLE Doctor DROP CONSTRAINT FK_cabinet
/*2*/
ALTER TABLE Doctor DROP COLUMN Id_cabinet
/*3*/
ALTER TABLE Patient ALTER COLUMN First_name char(30) NOT NULL;
/*4*/
ALTER TABLE Doctor ADD Email  Char(40)NULL
ALTER TABLE Film ADD CONSTRAINT UC_doctor UNIQUE(First_name,Second_name);
/*5*/
ALTER TABLE Appointment
ADD  CONSTRAINT  FK_patient FOREIGN KEY (Id_patient) 
REFERENCES Patient ON DELETE CASCADE ON UPDATE CASCADE,
ADD  CONSTRAINT  FK_doctor FOREIGN KEY (Id_doctor) 
REFERENCES Doctor ON DELETE CASCADE ON UPDATE CASCADE
